common: &COMMON
  env:
    RUSTFLAGS: -Dwarnings
    RUSTDOCFLAGS: -Dwarnings
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.lock || echo ""
  build_script:
    - cargo build $CARGO_ARGS
  test_script:
    # Mockall has unit tests in the examples, so we must pass --all-targets
    - cargo test $CARGO_ARGS --all-targets
  doc_script:
    - cargo doc $CARGO_ARGS --no-deps


task:
  matrix:
    - name: 1.42.0
      container:
        image: rust:1.42.0
    - name: stable
      container:
        image: rust:latest
  << : *COMMON
  before_cache_script: rm -rf $CARGO_HOME/registry/index

task:
  name: nightly
  container:
    image: rustlang/rust:nightly
  env:
    CARGO_ARGS: --all-features
  << : *COMMON
  lint_script:
    - rustup component add clippy
    - cargo clippy $CARGO_ARGS --all-targets --workspace -- -D warnings
  minver_script:
    - cargo update -Zminimal-versions
    - cargo test $CARGO_ARGS
  before_cache_script: rm -rf $CARGO_HOME/registry/index
