[package]
name = "mockall"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[features]
# Extra features for the nightly compiler only
nightly = []

[dependencies]
cfg-if = "0.1"
downcast = "0.9"
fragile = "0.3"
lazy_static = "1.0"
predicates = "1.0"
predicates-tree = "1.0"
mockall_derive = { path = "../mockall_derive" }
