[package]
name = "mockall_derive"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[package.metadata.docs.rs]
features = ["extra-docs"]

[features]
# Extra features for the nightly compiler only
nightly = ["proc-macro2/nightly"]
# For building documentation only; no functional change to the library.
extra-docs = []

[dependencies]
cfg-if = "0.1"
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15", features = ["extra-traits", "full"] }

[dev-dependencies]
downcast = "0.10"
fragile = "0.3"
mockall = { path = "../mockall" }
predicates-tree = "1.0"
pretty_assertions = "0.5"
