[package]
name = "mockall_derive"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[features]
# Extra features for the nightly compiler only
nightly = ["proc-macro2/nightly"]

[dependencies]
cfg-if = "0.1"
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15", features = ["full"] }

[dev-dependencies]
mockall = { path = "../mockall" }
pretty_assertions = "0.5"
