[package]
name = "mockall_derive"
version = "0.1.0"
authors = ["Alan Somers <asomers@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[features]
internal_testing = [ "pretty_assertions" ]

[dependencies]
mockall = { path = "../mockall" }
pretty_assertions = { version = "0.5", optional = true }
proc-macro2 = "0.4"
quote = "0.6"
syn = { version = "0.15", features = ["full"] }
